### ISSUE TITLE
Container creation failed: twingate : Depends: libnl-3-200 (>= 3.2.0) but it is not installable

### ISSUE THREAD

**Issue by nickperrott** [Twingate-Labs/tg-github-codespaces#1]
Hi, the combination of the split DNS provided by twingate running on a codespaces container looks like precisely what I need.

Unfortunately, I am having difficulties starting the codespaces container.

I have followed the readme instructions for establishing a service account/key based codespace, but container creation failed.

The full creation log is below:
```
=================================================================================
2023-04-19 00:24:21.554Z: Configuration starting...
2023-04-19 00:24:21.638Z: Cloning...
2023-04-19 00:24:21.687Z: $ git -C "/var/lib/docker/codespacemount/workspace" clone --branch "master" --depth 1 https://github.com/nickperrott/ewe-numera "/var/lib/docker/codespacemount/workspace/ewe-numera"
2023-04-19 00:24:21.719Z: Cloning into '/var/lib/docker/codespacemount/workspace/ewe-numera'...
2023-04-19 00:24:24.654Z: git process exited with exit code 0
2023-04-19 00:24:24.661Z: $ git -C "/var/lib/docker/codespacemount/workspace/ewe-numera" config --local remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
2023-04-19 00:24:24.667Z: git process exited with exit code 0

=================================================================================
2023-04-19 00:24:25.365Z: Creating container...
2023-04-19 00:24:25.377Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/ewe-numera --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --skip-post-create --config "/var/lib/docker/codespacemount/workspace/ewe-numera/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache
2023-04-19 00:24:25.609Z: @devcontainers/cli 0.37.0. Node.js v14.21.3. linux 5.4.0-1105-azure x64.
2023-04-19 00:24:26.474Z: $ docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.37.0-1681863866452/Dockerfile-with-features -t vsc-ewe-numera-02fe464689c351cab50b864ccf0e10c55d19e8e64a850c7ae259a3aecd36472f --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/ewe-numera
2023-04-19 00:24:27.028Z: #1 [internal] load .dockerignore
2023-04-19 00:24:27.318Z: #1 transferring context: 2B done
2023-04-19 00:24:27.419Z: #1 DONE 0.5s

#2 [internal] load build definition from Dockerfile-with-features
2023-04-19 00:24:27.424Z: #2 transferring dockerfile: 4.09kB 0.0s done
#2 DONE 0.5s
2023-04-19 00:24:27.541Z: 
2023-04-19 00:24:27.546Z: #3 [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/universal:linux
2023-04-19 00:24:29.197Z: #3 DONE 1.6s

2023-04-19 00:24:29.202Z: #4 [dev_container_auto_added_stage_label 1/2] FROM mcr.microsoft.com/vscode/devcontainers/universal:linux@sha256:78f1db9709d43ff5a6d6e2a8db4a7094e8420c871b24fae955b7b40686513bcd
#4 resolve mcr.microsoft.com/vscode/devcontainers/universal:linux@sha256:78f1db9709d43ff5a6d6e2a8db4a7094e8420c871b24fae955b7b40686513bcd
2023-04-19 00:24:29.347Z: #4 resolve mcr.microsoft.com/vscode/devcontainers/universal:linux@sha256:78f1db9709d43ff5a6d6e2a8db4a7094e8420c871b24fae955b7b40686513bcd 0.2s done
2023-04-19 00:24:38.218Z: #4 DONE 9.0s
2023-04-19 00:24:38.368Z: 
#5 [dev_container_auto_added_stage_label 2/2] RUN echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" | sudo tee /etc/apt/sources.list.d/twingate.list && sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/twingate.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" && sudo apt install -yq twingate
2023-04-19 00:24:38.940Z: #5 0.708 deb [trusted=yes] https://packages.twingate.com/apt/ /
2023-04-19 00:24:40.594Z: #5 2.300 Ign:1 https://packages.twingate.com/apt  InRelease
2023-04-19 00:24:40.746Z: #5 2.513 Ign:2 https://packages.twingate.com/apt  Release
2023-04-19 00:24:41.046Z: #5 2.725 Get:3 https://packages.twingate.com/apt  Packages
2023-04-19 00:24:41.299Z: #5 3.007 Fetched 20.9 kB in 2s (11.6 kB/s)
#5 3.007 Reading package lists...2023-04-19 00:24:41.305Z: 
#5 3.067 
#5 3.067 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#5 3.067 
2023-04-19 00:24:41.449Z: #5 3.089 Reading package lists...2023-04-19 00:24:41.455Z: 
#5 3.108 Building dependency tree...
#5 3.111 Reading state information...
#5 3.123 Some packages could not be installed. This may mean that you have
#5 3.123 requested an impossible situation or if you are using the unstable
#5 3.123 distribution that some required packages have not yet been created
#5 3.123 or been moved out of Incoming.
#5 3.123 The following information may help to resolve the situation:
#5 3.123 
#5 3.123 The following packages have unmet dependencies:
#5 3.124  twingate : Depends: libnl-3-200 (>= 3.2.0) but it is not installable
#5 3.124             Depends: libnl-route-3-200 (>= 3.2.0) but it is not installable
#5 3.125 E: Unable to correct problems, you have held broken packages.
2023-04-19 00:24:41.489Z: #5 ERROR: executor failed running [/bin/sh -c echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" | sudo tee /etc/apt/sources.list.d/twingate.list && sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/twingate.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" && sudo apt install -yq twingate]: exit code: 100
------
 > [dev_container_auto_added_stage_label 2/2] RUN echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" | sudo tee /etc/apt/sources.list.d/twingate.list && sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/twingate.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" && sudo apt install -yq twingate:
#5 3.123 Some packages could not be installed. This may mean that you have
#5 3.123 requested an impossible situation or if you are using the unstable
#5 3.123 distribution that some required packages have not yet been created
#5 3.123 or been moved out of Incoming.
#5 3.123 The following information may help to resolve the situation:
#5 3.123 
#5 3.123 The following packages have unmet dependencies:
#5 3.124  twingate : Depends: libnl-3-200 (>= 3.2.0) but it is not installable
#5 3.124             Depends: libnl-route-3-200 (>= 3.2.0) but it is not installable
#5 3.125 E: Unable to correct problems, you have held broken packages.
------
ERROR: failed to solve: executor failed running [/bin/sh -c echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" | sudo tee /etc/apt/sources.list.d/twingate.list && sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/twingate.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" && sudo apt install -yq twingate]: exit code: 100
2023-04-19 00:24:41.517Z: Stop: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.37.0-1681863866452/Dockerfile-with-features -t vsc-ewe-numera-02fe464689c351cab50b864ccf0e10c55d19e8e64a850c7ae259a3aecd36472f --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/ewe-numera
2023-04-19 00:24:41.521Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.37.0-1681863866452/Dockerfile-with-features -t vsc-ewe-numera-02fe464689c351cab50b864ccf0e10c55d19e8e64a850c7ae259a3aecd36472f --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/ewe-numera
2023-04-19 00:24:41.525Z:     at _se (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1917:1698)
2023-04-19 00:24:41.529Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-04-19 00:24:41.533Z:     at async CD (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1916:3889)
2023-04-19 00:24:41.539Z: {"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.37.0-1681863866452/Dockerfile-with-features -t vsc-ewe-numera-02fe464689c351cab50b864ccf0e10c55d19e8e64a850c7ae259a3aecd36472f --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/ewe-numera","description":"An error occurred building the image."}
2023-04-19 00:24:41.545Z: devcontainer process exited with exit code 1
2023-04-19 00:24:41.550Z:     at async K7 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1916:2808)
2023-04-19 00:24:41.554Z:     at async Hse (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1931:2626)
2023-04-19 00:24:41.570Z:     at async Ch (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1931:3741)
2023-04-19 00:24:41.571Z:     at async cae (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2059:17376)
2023-04-19 00:24:41.574Z:     at async uae (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2059:17117)

====================================== ERROR ====================================
2023-04-19 00:24:41.576Z: Failed to create container.
=================================================================================
2023-04-19 00:24:41.579Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.37.0-1681863866452/Dockerfile-with-features -t vsc-ewe-numera-02fe464689c351cab50b864ccf0e10c55d19e8e64a850c7ae259a3aecd36472f --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/ewe-numera
2023-04-19 00:24:41.584Z: Error Code: 1302

====================================== ERROR ====================================
2023-04-19 00:24:41.591Z: Container creation failed.
=================================================================================
```

**Comment by nickperrott** [comment]
I assume the issue is that the base image has changed since this repo was created.   I have tried against mcr.microsoft.com/devcontainers/python:3.9-buster, but I get even more errors.  See below:

```
#5 3.124 The following packages have unmet dependencies:
#5 3.125  twingate : Depends: libdbus-1-3 (>= 1.10) but it is not installable
#5 3.125             Depends: libnl-3-200 (>= 3.2.0) but it is not installable
#5 3.125             Depends: libnl-route-3-200 (>= 3.2.0) but it is not installable
#5 3.125             Depends: libcryptsetup12 but it is not installable

```

**Comment by emrul** [comment]
Hi @nickperrott - thanks for reporting this. We will take a look and update you on what the issue might be.

**Comment by andrew-stclair** [comment]
Are there any updates? This is still an issue

**Comment by JonParton** [comment]
Hey @emrul  / Twingate Team - I have also just tried to use this and hit the same issue above... Eeek!

**Comment by emrul** [comment]
Hi, I think this will be due to changes in the base image. @brendan-tg can you assign this as appropriate?
